
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alvar
 */
public class Portatiles extends javax.swing.JFrame {
    
    public DefaultListModel _listModel;

    /**
     * Creates new form Principal
     */
    public Portatiles() {
        initComponents();
        setLocationRelativeTo(null);
        
        _listModel = new DefaultListModel();
        _listModel.clear();
        lCesta.setModel(_listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        tTitulo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lStock = new javax.swing.JList<>();
        tStock = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lCesta = new javax.swing.JList<>();
        tCesta = new javax.swing.JTextField();
        bEliminar1 = new javax.swing.JButton();
        bEliminarTodo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bAñadir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        bPagar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mNavegación = new javax.swing.JMenu();
        mSobremesa = new javax.swing.JMenuItem();
        mPortatiles = new javax.swing.JMenuItem();
        mMoviles = new javax.swing.JMenuItem();
        mTablets = new javax.swing.JMenuItem();
        mComponentes = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenuItem();
        mCesta = new javax.swing.JMenu();
        mVisuCesta = new javax.swing.JMenuItem();
        mPagar = new javax.swing.JMenuItem();
        mInfo = new javax.swing.JMenu();
        mSobreN = new javax.swing.JMenuItem();
        mPregF = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tTitulo.setEditable(false);
        tTitulo.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        tTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tTitulo.setText("PORTÁTILES");
        tTitulo.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lStock.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Samsung Galaxy Book3 360 Intel Evo Core i7", "HP 15S-fq2159ns Intel Core i3", "Lenovo V15 IGL Intel Celeron N4020", "ASUS M515UA-EJ522W AMD Ryzen 5 5500U", "HP Victus 16-e0101ns AMD Ryzen 7 5800H" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lStock);

        tStock.setEditable(false);
        tStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tStock.setText("Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tStock)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(tStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        lCesta.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lCesta);

        tCesta.setEditable(false);
        tCesta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tCesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tCesta.setText("Cesta");

        bEliminar1.setText("Eliminar 1");
        bEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminar1ActionPerformed(evt);
            }
        });

        bEliminarTodo.setText("Eliminar todo");
        bEliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(tCesta, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bEliminarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tCesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEliminar1)
                    .addComponent(bEliminarTodo))
                .addGap(8, 8, 8))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        bAñadir.setText("Añadir a Cesta");
        bAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirActionPerformed(evt);
            }
        });
        jPanel3.add(bAñadir, new java.awt.GridBagConstraints());

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        bPagar.setText("Pagar");
        bPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mNavegación.setText("Navegación");

        mSobremesa.setText("PCs Sobremesa");
        mSobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSobremesaActionPerformed(evt);
            }
        });
        mNavegación.add(mSobremesa);

        mPortatiles.setText("Portátiles");
        mNavegación.add(mPortatiles);

        mMoviles.setText("Móviles");
        mNavegación.add(mMoviles);

        mTablets.setText("Tablets");
        mNavegación.add(mTablets);

        mComponentes.setText("Componentes");
        mNavegación.add(mComponentes);

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mNavegación.add(mSalir);

        jMenuBar1.add(mNavegación);

        mCesta.setText("Cesta");

        mVisuCesta.setText("Visualizar Cesta");
        mVisuCesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVisuCestaActionPerformed(evt);
            }
        });
        mCesta.add(mVisuCesta);

        mPagar.setText("Pagar");
        mPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPagarActionPerformed(evt);
            }
        });
        mCesta.add(mPagar);

        jMenuBar1.add(mCesta);

        mInfo.setText("Información");

        mSobreN.setText("Sobre nosotros");
        mInfo.add(mSobreN);

        mPregF.setText("Preguntas frecuentes");
        mInfo.add(mPregF);

        jMenuBar1.add(mInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tTitulo)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirActionPerformed
        String producto = lStock.getSelectedValue();
        _listModel.add(_listModel.getSize(), producto);
    }//GEN-LAST:event_bAñadirActionPerformed

    private void bEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminar1ActionPerformed
        String producto = lCesta.getSelectedValue();
        _listModel.removeElement(producto);
    }//GEN-LAST:event_bEliminar1ActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mSalirActionPerformed

    private void bEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarTodoActionPerformed
        _listModel.removeAllElements();
    }//GEN-LAST:event_bEliminarTodoActionPerformed

    private void mVisuCestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVisuCestaActionPerformed
        Cesta cesta = new Cesta();
        cesta.lCesta1.add(lCesta);
        cesta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mVisuCestaActionPerformed

    private void bPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPagarActionPerformed
        Pagar pagar = new Pagar();
        pagar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bPagarActionPerformed

    private void mPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPagarActionPerformed
        Pagar pagar = new Pagar();
        pagar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mPagarActionPerformed

    private void mSobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSobremesaActionPerformed
        PCsobremesa pcsobremesa = new PCsobremesa();
        pcsobremesa.lCesta.add(lCesta);
        pcsobremesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mSobremesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PCsobremesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PCsobremesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PCsobremesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PCsobremesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PCsobremesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bEliminar1;
    private javax.swing.JButton bEliminarTodo;
    private javax.swing.JButton bPagar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JList<String> lCesta;
    private javax.swing.JList<String> lStock;
    private javax.swing.JMenu mCesta;
    private javax.swing.JMenuItem mComponentes;
    private javax.swing.JMenu mInfo;
    private javax.swing.JMenuItem mMoviles;
    private javax.swing.JMenu mNavegación;
    private javax.swing.JMenuItem mPagar;
    private javax.swing.JMenuItem mPortatiles;
    private javax.swing.JMenuItem mPregF;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenuItem mSobreN;
    private javax.swing.JMenuItem mSobremesa;
    private javax.swing.JMenuItem mTablets;
    private javax.swing.JMenuItem mVisuCesta;
    private javax.swing.JTextField tCesta;
    private javax.swing.JTextField tStock;
    private javax.swing.JTextField tTitulo;
    // End of variables declaration//GEN-END:variables
}
